site_name: curry
repo_url: https://github.com/lakodo/curry
site_url: https://lakodo.github.io/curry
site_description: Wrap dask scheduler to make it easy to buid datascience flow
site_author: Joris GUERRY
edit_uri: edit/main/docs/
repo_name: lakodo/curry
copyright: Maintained by <a href="https://lakodo.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
              - import sys
              - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lakodo/curry
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/curry

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
