"""second

Revision ID: 62aa2eab86c4
Revises: 0272aba68386
Create Date: 2024-09-23 22:55:13.640528

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62aa2eab86c4"
down_revision: Union[str, None] = "0272aba68386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hero", "truc")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hero", sa.Column("truc", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
